In [5]:
print("Hallo world")

Hallo world


In [1]:
print("My name is Alexey")

My name is Alexey


# Заголовок 1
## Заголовок 2
Это *курсив*
Это **полужирный**
- элемент 1
- элемент 2
    - подэлемент 2
- элемент 3

In [3]:
import numpy as np

In [9]:
a = np.array([1,66,2,9.2, 8, 9, 21], float)
print(len(a))

7


In [11]:
np.insert(a, 2, [34, 75])

array([ 1. , 66. , 34. , 75. ,  2. ,  9.2,  8. ,  9. , 21. ])

In [12]:
np.delete(a, 1)

array([ 1. ,  2. ,  9.2,  8. ,  9. , 21. ])

In [13]:
a = np.insert(a, 2, [34, 75])
print(a)

[ 1.  66.  34.  75.   2.   9.2  8.   9.  21. ]


In [14]:
b = np.insert(a, 5, [77])

In [15]:
print(b)

[ 1.  66.  34.  75.   2.  77.   9.2  8.   9.  21. ]


In [16]:
b.sort()

In [17]:
print(b)

[ 1.   2.   8.   9.   9.2 21.  34.  66.  75.  77. ]


In [4]:
np.random.rand(3,2)

array([[0.46563153, 0.9648511 ],
       [0.14289821, 0.9362649 ],
       [0.95481597, 0.24163258]])

In [5]:
np_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np_array[-1]

9

In [11]:
np_array[0:8:3]

array([0, 3, 6])

In [17]:
x = np.array(
             [
                 [1, 1],
                 [0, 1]
             ]
            )

In [18]:
x.shape

(2, 2)

In [19]:
np_array.shape

(10,)

In [20]:
x.ndim

2

In [21]:
x.size

4

In [22]:
np_array.size

10

In [24]:
x1 = np_array.reshape(2, 5)

In [25]:
x1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
x2 = np_array.reshape(2, -1)
x2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
np_array + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
np_array * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
np_array * 10 + 9

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [31]:
x = np.arange(0, 100, 10)

In [32]:
x

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
x - np_array

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81])

In [34]:
np.sin(np_array)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [44]:
y = np.arange(0,3.1415926*2, 3.1415925/50)

In [45]:
y

array([0.        , 0.06283185, 0.1256637 , 0.18849555, 0.2513274 ,
       0.31415925, 0.3769911 , 0.43982295, 0.5026548 , 0.56548665,
       0.6283185 , 0.69115035, 0.7539822 , 0.81681405, 0.8796459 ,
       0.94247775, 1.0053096 , 1.06814145, 1.1309733 , 1.19380515,
       1.256637  , 1.31946885, 1.3823007 , 1.44513255, 1.5079644 ,
       1.57079625, 1.6336281 , 1.69645995, 1.7592918 , 1.82212365,
       1.8849555 , 1.94778735, 2.0106192 , 2.07345105, 2.1362829 ,
       2.19911475, 2.2619466 , 2.32477845, 2.3876103 , 2.45044215,
       2.513274  , 2.57610585, 2.6389377 , 2.70176955, 2.7646014 ,
       2.82743325, 2.8902651 , 2.95309695, 3.0159288 , 3.07876065,
       3.1415925 , 3.20442435, 3.2672562 , 3.33008805, 3.3929199 ,
       3.45575175, 3.5185836 , 3.58141545, 3.6442473 , 3.70707915,
       3.769911  , 3.83274285, 3.8955747 , 3.95840655, 4.0212384 ,
       4.08407025, 4.1469021 , 4.20973395, 4.2725658 , 4.33539765,
       4.3982295 , 4.46106135, 4.5238932 , 4.58672505, 4.64955

In [46]:
np.sin(y)

array([ 0.00000000e+00,  6.27905165e-02,  1.25333227e-01,  1.87381306e-01,
        2.48689875e-01,  3.09016980e-01,  3.68124536e-01,  4.25779272e-01,
        4.81753653e-01,  5.35826772e-01,  5.87785227e-01,  6.37423964e-01,
        6.84547079e-01,  7.28968600e-01,  7.70513215e-01,  8.09016967e-01,
        8.44327899e-01,  8.76306655e-01,  9.04827029e-01,  9.29776464e-01,
        9.51056497e-01,  9.68583145e-01,  9.82287238e-01,  9.92114692e-01,
        9.98026724e-01,  1.00000000e+00,  9.98026733e-01,  9.92114712e-01,
        9.82287267e-01,  9.68583183e-01,  9.51056545e-01,  9.29776521e-01,
        9.04827094e-01,  8.76306729e-01,  8.44327981e-01,  8.09017058e-01,
        7.70513313e-01,  7.28968705e-01,  6.84547191e-01,  6.37424082e-01,
        5.87785352e-01,  5.35826901e-01,  4.81753787e-01,  4.25779411e-01,
        3.68124678e-01,  3.09017126e-01,  2.48690024e-01,  1.87381456e-01,
        1.25333380e-01,  6.27906698e-02,  1.53589793e-07, -6.27903632e-02,
       -1.25333075e-01, -

In [48]:
y.max()

6.283185

In [50]:
sin_y = np.sin(y)

In [51]:
sin_y.max()

0.999999999999997

In [52]:
y.argmax()

100

In [53]:
sin_y.argmax()

25

In [54]:
np_array *= 3

In [55]:
np_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [61]:
z = np.array(
             [
                 [2, 0],
                 [1, 4]
             ]
            )

In [62]:
z

array([[2, 0],
       [1, 4]])

In [63]:
z.mean()

1.75

In [64]:
z.mean(axis=1)

array([1. , 2.5])

In [65]:
z.max(axis = 0)

array([2, 4])

In [68]:
A = np.array(
             [
                 [1, 1],
                 [0, 1]
             ]
            )

B = np.array(
             [
                 [2, 0],
                 [3, 4]
             ]
            )

A * B #Поэлементное перемножение

array([[2, 0],
       [0, 4]])

In [69]:
A @ B

array([[5, 4],
       [3, 4]])

In [70]:
B @ A

array([[2, 2],
       [3, 7]])

In [71]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [72]:
A.dot(B).T

array([[5, 3],
       [4, 4]])

In [73]:
A.dot(B.T)

array([[2, 7],
       [0, 4]])

In [78]:
vst = np.vstack((A,B))
vst

array([[1, 1],
       [0, 1],
       [2, 0],
       [3, 4]])

In [81]:
hst = np.hstack((A,B))
hst

array([[1, 1, 2, 0],
       [0, 1, 3, 4]])

In [83]:
np.vsplit(vst, 4)

[array([[1, 1]]), array([[0, 1]]), array([[2, 0]]), array([[3, 4]])]

In [84]:
np.hsplit(hst, 4)

[array([[1],
        [0]]),
 array([[1],
        [1]]),
 array([[2],
        [3]]),
 array([[0],
        [4]])]

In [85]:
np.hsplit(hst, 2)

[array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [3, 4]])]

In [86]:
import pandas as pd

In [87]:
s = pd.Series(np.arange(5), index=["a", "b", "c", "d", "e"])

In [88]:
s

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [90]:
my_df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
my_df

A  B
0  1  4
1  2  5
2  3  6

In [91]:
df

A  B
0  1  4
1  2  5
2  3  6

In [93]:
s['b']

1

In [106]:
df = pd.DataFrame({
    "A": pd.Series([0.0, 2.0, 3.0, 4.0, 5.0], index=["a", "b", "c", "d", "e"]),
    "B": pd.Series([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], index=["a", "b", "c", "d", "e", "f"]),
})
df

A    B
a  0.0  1.0
b  2.0  2.0
c  3.0  3.0
d  4.0  4.0
e  5.0  5.0
f  NaN  6.0

In [95]:
df.head()

A    B
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  4.0  4.0
e  5.0  5.0

In [96]:
df.head(3)

A    B
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0

In [97]:
df.tail(4)

A    B
c  3.0  3.0
d  4.0  4.0
e  5.0  5.0
f  NaN  6.0

In [98]:
df.describe()

A         B
count  5.000000  6.000000
mean   3.000000  3.500000
std    1.581139  1.870829
min    1.000000  1.000000
25%    2.000000  2.250000
50%    3.000000  3.500000
75%    4.000000  4.750000
max    5.000000  6.000000

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, a to f
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       5 non-null      float64
 1   B       6 non-null      float64
dtypes: float64(2)
memory usage: 144.0+ bytes


In [100]:
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [101]:
df['A'].value_counts()

1.0    1
2.0    1
3.0    1
4.0    1
5.0    1
Name: A, dtype: int64

In [102]:
df['B'].value_counts()

1.0    1
2.0    1
3.0    1
4.0    1
5.0    1
6.0    1
Name: B, dtype: int64

In [108]:
df.isna()

A      B
a  False  False
b  False  False
c  False  False
d  False  False
e  False  False
f   True  False

In [107]:
df.isna().sum()

A    1
B    0
dtype: int64

In [105]:
df.T

a    b    c    d    e    f
A  1.0  2.0  3.0  4.0  5.0  NaN
B  1.0  2.0  3.0  4.0  5.0  6.0

In [110]:
df.T.index

Index(['A', 'B'], dtype='object')

In [111]:
df["A"]

a    0.0
b    2.0
c    3.0
d    4.0
e    5.0
f    NaN
Name: A, dtype: float64

In [112]:
df.sort_values(by='A', ascending=True)

A    B
a  0.0  1.0
b  2.0  2.0
c  3.0  3.0
d  4.0  4.0
e  5.0  5.0
f  NaN  6.0

In [113]:
df.sort_values(by='B', ascending=False)

A    B
f  NaN  6.0
e  5.0  5.0
d  4.0  4.0
c  3.0  3.0
b  2.0  2.0
a  0.0  1.0

In [115]:
#df[0] очень жесткая ошибка - сразу выдает кучу красных строк
df[0:3]

A    B
a  0.0  1.0
b  2.0  2.0
c  3.0  3.0

In [118]:
df[0:1]

A    B
a  0.0  1.0

In [120]:
df[2:4]

A    B
c  3.0  3.0
d  4.0  4.0

In [125]:
df["a":"c"]

A    B
a  0.0  1.0
b  2.0  2.0
c  3.0  3.0

In [128]:
df["c":"f"]

A    B
c  3.0  3.0
d  4.0  4.0
e  5.0  5.0
f  NaN  6.0

In [143]:
df.iloc[1,1]

2.0

In [145]:
df["A"]>3

a    False
b    False
c    False
d     True
e     True
f    False
Name: A, dtype: bool

In [148]:
j= df[df["A"]>3]
j

A    B
d  4.0  4.0
e  5.0  5.0

In [149]:
df['C'] = df['A'] + df['B']
df

A    B     C
a  0.0  1.0   1.0
b  2.0  2.0   4.0
c  3.0  3.0   6.0
d  4.0  4.0   8.0
e  5.0  5.0  10.0
f  NaN  6.0   NaN

In [151]:
df_droppedna = df.dropna()
df_droppedna

A    B     C
a  0.0  1.0   1.0
b  2.0  2.0   4.0
c  3.0  3.0   6.0
d  4.0  4.0   8.0
e  5.0  5.0  10.0

In [152]:
df_filled = df.fillna(value = df.mean())
df_filled

A    B     C
a  0.0  1.0   1.0
b  2.0  2.0   4.0
c  3.0  3.0   6.0
d  4.0  4.0   8.0
e  5.0  5.0  10.0
f  2.8  6.0   5.8

In [154]:
df.mean(1)

a    0.666667
b    2.666667
c    4.000000
d    5.333333
e    6.666667
f    6.000000
dtype: float64

In [155]:
df.median()

A    3.0
B    3.5
C    6.0
dtype: float64

In [156]:
df

A    B     C
a  0.0  1.0   1.0
b  2.0  2.0   4.0
c  3.0  3.0   6.0
d  4.0  4.0   8.0
e  5.0  5.0  10.0
f  NaN  6.0   NaN

In [158]:
df.shift(periods=1)

A    B     C
a  NaN  NaN   NaN
b  0.0  1.0   1.0
c  2.0  2.0   4.0
d  3.0  3.0   6.0
e  4.0  4.0   8.0
f  5.0  5.0  10.0

In [159]:
df['A'] - df['A'].shift(periods=1)

a    NaN
b    2.0
c    1.0
d    1.0
e    1.0
f    NaN
Name: A, dtype: float64

In [162]:
df.apply(np.cumsum)

A     B     C
a   0.0   1.0   1.0
b   2.0   3.0   5.0
c   5.0   6.0  11.0
d   9.0  10.0  19.0
e  14.0  15.0  29.0
f   NaN  21.0   NaN

In [167]:
df.apply(lambda x: np.cumsum(x) % 5)

A    B    C
a  0.0  1.0  1.0
b  2.0  3.0  0.0
c  0.0  1.0  1.0
d  4.0  0.0  4.0
e  4.0  0.0  4.0
f  NaN  1.0  NaN